### ISSUE TITLE
[BC-BREAK] scriptfusion/retry 1.1.2

### ISSUE THREAD

**Issue by samvdb** [ScriptFUSION/Porter#55]
Hi,

When running porter 3.* retry 1.1.2 will be installed because of the following composer requirement:

```json
"scriptfusion/retry": "^1.1",
```

The retry lib works on 1.1.1 with porter, upgrading to 1.1.2 breaks stuff.

Specific lines in the retry lib that are triggered:

```php
if ($result instanceof \Generator) {
            throw new \UnexpectedValueException('Cannot retry a Generator. You probably meant something else.');
        }
```

Porter causes this because a generator is returned in Porter.php line 98

```php
function () use ($provider, $resource) {
                if (($records = $provider->fetch($resource)) instanceof \Iterator) {
                    // Force generator to run until first yield to provoke an exception.
                    $records->valid();
                }

                return $records;     <----- this breaks
            },
```

**Comment by Bilge** [comment]
I guess you mean Retry `1.2.0`?

**Comment by Bilge** [comment]
Thanks, @samvdb. I've looked into this and it seems you're correct. That's my fault: I should have bumped the version number for *Retry* to 2.0.0, not 1.2.0. I'll try deleting the 1.2.0 tag and retagging as 2.0.0 for you. 

Keep in mind that the exception message is correct: you cannot retry a generator. This was a design flaw in Porter 3 that is fixed in v4. I hope you will be able to upgrade to v4 and enjoy its improved architecture and fixes soon!
